CREATE TABLE `ta`.`course` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `fee` VARCHAR(255) NOT NULL , `desc` VARCHAR(255) NOT NULL , `dt` INT NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB
ALTER TABLE `course` CHANGE `dt` `dt` DATETIME(11) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `course` CHANGE `dt` `dt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE `ta`.`student` ( `id` INT(11) NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `pass` VARCHAR(255) NOT NULL , `dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `student` (`id`, `name`, `pass`, `dt`) VALUES ('1', 'suraj', '123', current_timestamp());